### ISSUE TITLE
Move coding style disclaimer to root directory

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#106]
1. #97 adds coding style disclaimer. It should reside under the root directory, i.e. wallchain directory.
2. Fix the grammar error, e.g. ...is mostly obeyed...
3. Use GitHub markdown grammar for hyperlink instead of posting the link blatantly, e.g. [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html)

**Comment by jameslu77** [comment]
Done at PR #101.
[ISSUE-106.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2401748/ISSUE-106.000.patch.txt)
[ISSUE-106.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2401749/ISSUE-106.001.patch.txt)
