### ISSUE TITLE
There are some github grammar errors in README.md

### ISSUE THREAD

**Issue by jameslu77** [wallchainfoundation/wallchain#116]
Please fix them. See [README.md](https://github.com/wallchainfoundation/wallchain/blob/master/README.md)

**Comment by xiaobingo** [comment]
@jameslu77 could you please point out specific errors for clarity? Thanks.

**Comment by jameslu77** [comment]
Some errors like:
####Windows
####Mac OS X
####Linux

**Comment by wupeng191** [comment]
Done at PR #124 . See [README.md](https://github.com/wallchainfoundation/wallchain/blob/dev_wupeng/README.md).

**Comment by jameslu77** [comment]
It's OK.
