### ISSUE TITLE
Make ServiceRegistry thread safe

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#128]
As follow-up work of #112, ServiceRegistry::PutXXX/GetXXX should be thread safe.

**Comment by jameslu77** [comment]
@wupeng191  Please make sure that ./test_rpc is pass through before committing. Thx!

**Comment by edsburke** [comment]
@wupeng191, you could have two ways:
1.  Use lock inside.
2. Use some concurrent map, e.g. from folly or Threading Building Blocks

Approach 2 should be easier since they are well-tested.

**Comment by wupeng191** [comment]
Ok, folly::ConcurrentHashMap is this solution.
Done at PR #191 .
[ISSUE-128.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2430318/ISSUE-128.001.patch.txt)
