### ISSUE TITLE
Implement a service prototype using service registration and PB service auto-generation

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#143]
To better instruct how to write concrete RPC service implementation, this proposes implementing a service prototype using service registration and PB service auto-generation.

See also #112

**Comment by edsburke** [comment]
Posted [ISSUE-143.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2420968/ISSUE-143.001.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-143.002.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2421329/ISSUE-143.002.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-143.003.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2421350/ISSUE-143.003.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-143.004.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2421860/ISSUE-143.004.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-143.005.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2422067/ISSUE-143.005.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-143.006.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2422104/ISSUE-143.006.patch.txt)

**Comment by edsburke** [comment]
Resolve this due to #169
