### ISSUE TITLE
Add a unit test to use default constructor of NodeConnection

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#189]
```
NodeConnection::NodeConnection()
```
should also be tested, e.g.
```
TEST(NodeConnectionTest, DefaultConstructor) {
```
In this case, NodeConnection::Start() will be successful, then verify other empty stuff, e.g.
```
Contact contact = node_connection.GetContact();
// contact is empty...
```

**Comment by jameslu77** [comment]
Actual NodeConnection is used to manage PRC operations of a node, then there must be a node with a specified listening port before creating the corresponding NodeConnection. So I think we should remove the DefaultConstructor of a node. What's your opinion?

**Comment by jameslu77** [comment]
Done at PR #200.
[ISSUE-189.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2431203/ISSUE-189.000.patch.txt)
