### ISSUE TITLE
Rename test setting in wallchain::rpc::RpcSerde 

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#216]
HBASE_CLIENT_RPC_TEST_MODE should be renamed to 

```
wallchain::rpc::RpcSerde::WALLCHAIN_CLIENT_RPC_TEST_MODE
```

**Comment by jameslu77** [comment]
Done at PR #246.
[ISSUE-216.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2437357/ISSUE-216.000.patch.txt)
