### ISSUE TITLE
Rename node-rpc-service-impl.h to node-rpc-server.h

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#228]
xxx-impl.h is where template classes/functions implementation reside.  In the bottom of xxx.h is included xxx-impl.h.

**Comment by edsburke** [comment]
Resolve this due #230

**Comment by jameslu77** [comment]
Actually it makes more sense to use the original name. 
I had changed it back at PR #237.
[ISSUE-228.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2436273/ISSUE-228.001.patch.txt)
