### ISSUE TITLE
Suppress warning of unused parameters

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#229]
If a parameter is not used in a function, there will be warning like this which is annoying. Should be suppressed.

/usr/src/wallchain-ws/wallchain/dht/src/routing/src/wallchain/routing/node-rpc-client.cc:28:35: error: unused parameter 'peer' [-Werror=unused-parameter]
 void NodeRpc::Ping(const Contact &peer,
                                   ^
/usr/src/wallchain-ws/wallchain/dht/src/routing/src/wallchain/routing/node-rpc-client.cc:29:35: error: unused parameter 'callback' [-Werror=unused-parameter]
                    RpcPingFunctor callback) {

**Comment by jameslu77** [comment]
The issue resolved when implementing NodeRpcClient.
See also at #240.
