### ISSUE TITLE
Flaky failure of TcpTest.BEH_UnavailablePort

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#23]
The testcase TcpTest.BEH_UnavailablePort fails with Segmentation fault.

To reproduce, just run test_common for a couple of times.

**Comment by jameslu77** [comment]
It seems that this issue is a rare case in some condition or runtime environment. I can't reproduce it after trying many times. No matter running ./test_common or ./test_common --gtest_filter=TcpTest.BEH_UnavailablePort. It needs more time to look into anyway.

**Comment by jameslu77** [comment]
Won't use tcp in common any more.
