### ISSUE TITLE
Add PingTarget test for NodeRpcClientTest

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#234]
As follow-up work of #227, This test 
```
TEST_P(NodeRpcClientTest, PingTarget) {
  bool done(false);
  ReturnCode response_code(ReturnCode::kGeneralError);

  node_rpc_client_.Ping(service_contact_,
                        std::bind(&TestCallback, args::_1, args::_2, &done, &response_code));

  EXPECT_EQ(ReturnCode::kSuccess, response_code);
}
```
will throw error which need to be fixed, e.g.:

I1002 00:36:09.543239  7632 connection-pool.cc:101] Closing RPC Connection to host:0.0.0.0, port:0
/usr/src/wallchain-ws/wallchain/dht/src/routing/test/wallchain/routing/node-rpc-client-test.cc:103: Failure
Value of: response_code
  Actual: 4-byte object <5A-60 FB-FF>
Expected: ReturnCode::kSuccess
Which is: 4-byte object <00-00 00-00>
To potentially replicate the failure, try re-running with:
   --gtest_filter=SingleKValue/NodeRpcClientTest.PingTarget/0 --seed 3390219227
[  FAILED  ] SingleKValue/NodeRpcClientTest.PingTarget/0, where GetParam() = 2 (3 ms)

**Comment by jameslu77** [comment]
The issue resolved when implementing NodeRpcClient.
See also at #240.
