### ISSUE TITLE
Build test environment architecture: LocalNetwork

### ISSUE THREAD

**Issue by jameslu77** [wallchainfoundation/wallchain#250]

**Comment by jameslu77** [comment]
Done at PR #251.
[ISSUE-250.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2437928/ISSUE-250.000.patch.txt)

**Comment by edsburke** [comment]
[ISSUE-250.001.txt](https://github.com/wallchainfoundation/wallchain/files/2454458/ISSUE-250.001.txt)
