### ISSUE TITLE
Implement Node and NodeContainer structure

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#255]

**Comment by edsburke** [comment]
[ISSUE-255.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2439328/ISSUE-255.000.patch.txt)

**Comment by edsburke** [comment]
[ISSUE-255.002.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2440044/ISSUE-255.002.patch.txt)

**Comment by edsburke** [comment]
@jameslu77  please continue work on this patch. Pls deprecate #235.

The goal of this patch is to implement Node and NodeContainer structure targeting Ping method, however, in order to make NodeContainer and LocalNetwork work, Join must be implemented as well.

**Comment by jameslu77** [comment]
[ISSUE-255.003.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2442874/ISSUE-255.003.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-255.004.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2443434/ISSUE-255.004.patch.txt). It resolves all compile errors.

**Comment by edsburke** [comment]
Posted [ISSUE-255.005.txt](https://github.com/wallchainfoundation/wallchain/files/2444326/ISSUE-255.005.txt), which passes tests.

**Comment by edsburke** [comment]
[ISSUE-255.006.txt](https://github.com/wallchainfoundation/wallchain/files/2444497/ISSUE-255.006.txt)
Enhancedment patch.

**Comment by edsburke** [comment]
[ISSUE-255.007.txt](https://github.com/wallchainfoundation/wallchain/files/2444539/ISSUE-255.007.txt)
Adds Join skeleton.

**Comment by edsburke** [comment]
@jameslu77, you need to fill Node::Join and NodeContainer::Join part.

**Comment by jameslu77** [comment]
[ISSUE-255.008.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2447469/ISSUE-255.008.patch.txt)

**Comment by jameslu77** [comment]
[ISSUE-255.009.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2451256/ISSUE-255.009.patch.txt)

**Comment by jameslu77** [comment]
[ISSUE-255.009.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2453283/ISSUE-255.009.patch.txt)

**Comment by jameslu77** [comment]
This 010 patch has an error git operation, that is git rebase recently modification of ISSUE-255 into ISSUE-250 as a new commit.
[ISSUE-255.010.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2454180/ISSUE-255.010.patch.txt)

**Comment by edsburke** [comment]
Thanks @jameslu77 for the v10 patch. Some comments:
1. StartLookup is not called.
```
void NodeImpl::Join(
  std::vector<Contact> bootstrap_contacts,
  JoinFunctor callback) {

....
//  StartLookup(find_nodes_args);
```
2. what's the purpose of '--lookup_args->total_lookup_rpcs_in_flight;'?
```
void NodeImpl::IterativeFindCallback(
    RankInfoPtr rank_info,
    ReturnCode result,
    const std::vector<Contact> &contacts,
    const Contact &cached_copy_holder,
    Contact peer,
    LookupArgsPtr lookup_args) {

--lookup_args->total_lookup_rpcs_in_flight;
``

**Comment by jameslu77** [comment]
[ISSUE-255.010-011.txt](https://github.com/wallchainfoundation/wallchain/files/2456880/ISSUE-255.010-011.txt)

**Comment by edsburke** [comment]
@jameslu77 thanks for the patch. A quick question is why you comment out this line?
```
oid NodeImpl::Join(
  std::vector<Contact> bootstrap_contacts,
  JoinFunctor callback) {

//  routing_table_.reset(new RoutingTable(node_id, k_));
```

**Comment by edsburke** [comment]
And what's the reason why there's no equivalent code block for the following in v10 patch?
```
void NodeImpl::Join(
  std::vector<Contact> bootstrap_contacts,
  JoinFunctor callback) {

// TODO(Fraser#5#): 2011-07-08 - Need to update code for local endpoints.
  if (!client_only_node_) {
    std::vector<transport::Endpoint> local_endpoints;
    // Create contact_ information for node and set contact for Rpcs
    transport::Endpoint endpoint;
    endpoint.ip = listening_transport_->transport_details().endpoint.ip;
    endpoint.port = listening_transport_->transport_details().endpoint.port;
    local_endpoints.push_back(endpoint);
    contact_ =
        Contact(node_id, endpoint, local_endpoints,
                listening_transport_->transport_details().rendezvous_endpoint,
                false, false, node_id.String(),
                *default_public_key_, "");
    rpcs_->set_contact(contact_);
  } else {
    contact_ = Contact(node_id, transport::Endpoint(),
                       std::vector<transport::Endpoint>(),
                       transport::Endpoint(), false, false,
                       node_id.String(),
                       *default_public_key_, "");
    protobuf::Contact proto_contact(ToProtobuf(contact_));
    proto_contact.set_node_id(NodeId().String());
    rpcs_->set_contact(FromProtobuf(proto_contact));
  }
```

**Comment by edsburke** [comment]
And one more thing that is quite different is:
```
template <typename NodeType>
ReturnCode NodeContainer<NodeType>::Stop(std::vector<Contact> *bootstrap_contacts) {

//  try {
//    if (node_->joined()) {
//      node_->Leave(&bootstrap_contacts_);
//      if (bootstrap_contacts)
//        *bootstrap_contacts = bootstrap_contacts_;
//    }
//  } catch(const std::exception&) {
//    return kGeneralError;
//  }
```

This may cause problems.

**Comment by edsburke** [comment]
[ISSUE-255.010-011.001.txt](https://github.com/wallchainfoundation/wallchain/files/2457163/ISSUE-255.010-011.001.txt)  un-comment out this in 
```
template <typename NodeType>
void NodeContainer<NodeType>::JoinCallback(
    ReturnCode result_in,
    boost::mutex *mutex,
    boost::condition_variable *cond_var) {

> +//  std::cout << "before NodeContainer<NodeType>::JoinCallback mutex" << std::endl;
> +//  boost::mutex::scoped_lock lock(*mutex);
> +//  std::cout << "after NodeContainer<NodeType>::JoinCallback mutex" << std::endl;
```

**Comment by edsburke** [comment]
[ISSUE-255.010-011.002.txt](https://github.com/wallchainfoundation/wallchain/files/2458362/ISSUE-255.010-011.002.txt) Uses instance variables instead of local ones.

```
+++ b/dht/src/routing/include/wallchain/routing/node-container-impl.h
@@ -40,7 +40,9 @@ NodeContainer<NodeType>::NodeContainer(uint8_t thread_count)
       gotten_contact_(),
       wait_for_ping_functor_(),
       ping_functor_(),
-      join_functor_() {
+      join_functor_(),
+      mutex_(),
+      cond_var_() {
```

```
template <typename NodeType>
ReturnCode NodeContainer<NodeType>::Start(
    const std::vector<Contact> &bootstrap_contacts,
    std::pair<uint16_t, uint16_t> port_range) {
-  boost::mutex mutex;
-  boost::condition_variable cond_var;
   JoinFunctor join_functor(std::bind(
       &NodeContainer<NodeType>::JoinCallback,
-      this, args::_1, &mutex, &cond_var));
+      this, args::_1, &mutex_, &cond_var_));
```

This resolves an error like the following which means [locking a mutex that has been destroyed / hasn't been initialized](https://stackoverflow.com/questions/1105745/pthread-mutex-assertion-error)

test_routing: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

**Comment by edsburke** [comment]
[ISSUE-255.010-011.004.txt](https://github.com/wallchainfoundation/wallchain/files/2458627/ISSUE-255.010-011.004.txt) prints out thread id for debug.

**Comment by jameslu77** [comment]
[ISSUE-255.010-011.005.txt](https://github.com/wallchainfoundation/wallchain/files/2461344/ISSUE-255.010-011.005.txt)

**Comment by jameslu77** [comment]
[ISSUE-255.010-011.007.txt](https://github.com/wallchainfoundation/wallchain/files/2474009/ISSUE-255.010-011.007.txt)
Add more tests in node-test.cc.
Timeout problem still exists.

**Comment by jameslu77** [comment]
[ISSUE-255.011.txt](https://github.com/wallchainfoundation/wallchain/files/2475010/ISSUE-255.011.txt)
[ISSUE-255.011-012.000.txt](https://github.com/wallchainfoundation/wallchain/files/2475011/ISSUE-255.011-012.000.txt)
[ISSUE-255.012.txt](https://github.com/wallchainfoundation/wallchain/files/2475012/ISSUE-255.012.txt)

**Comment by edsburke** [comment]
[ISSUE-255.011-012.001.txt](https://github.com/wallchainfoundation/wallchain/files/2475053/ISSUE-255.011-012.001.txt) removes some log messages being commented out.

**Comment by edsburke** [comment]
[ISSUE-255.012.txt](https://github.com/wallchainfoundation/wallchain/files/2475056/ISSUE-255.012.txt)  merges ISSUE-255.011-012.001.txt

**Comment by edsburke** [comment]
[ISSUE-255.013.txt](https://github.com/wallchainfoundation/wallchain/files/2475063/ISSUE-255.013.txt)
1. removes all empty spaces or tabs
2. removes all code snippets being commented out.

**Comment by edsburke** [comment]
Resolve this due to #268.
