### ISSUE TITLE
"Killed" error when adding 100 nodes

### ISSUE THREAD

**Issue by jameslu77** [wallchainfoundation/wallchain#333]
When adding 100 nodes in docker environment, there is "Killed" error. I guess that is a memory error. Need further research.

**Comment by jameslu77** [comment]
To find the reason of "Killed", we must browse the /var/log/syslog. Unfortunately, there's no this file in Wallchain docker environment. We have to install and start rsyslog in docker by:
```
apt-get install rsyslog 
service rsyslog start
``` 
Run the test again to reproduce the "Killed" error, then we can find the error reason by:
```
tail /var/log/syslog
...
Nov  3 04:06:58 securecluster kernel: Out of memory: Kill process 24412 (test_routing) 
Nov  3 04:06:58 securecluster kernel: Killed process 24412 (test_routing) total-vm:12191220kB 
...
```
Obviously, that's a memory issue.

**Comment by edsburke** [comment]
Mark this with bank to be revisited later.
