### ISSUE TITLE
Hook cmake of RPC module into the parent module

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#34]
#31 adds independent cmake for RPC module, it should be hooked into the parent module (i.e. src/dht) so that we invoke build all at once.

**Comment by jameslu77** [comment]
Now the Rpc is totally imported into the project and can build Rpc module by running: make AllRpc.
And the other modules can also use Rpc functions by reference Rpc. An example is the z_rpc_test.cc in the Routing. Check details in PR #40.

**Comment by xiaobingo** [comment]
This has been reopened because with commit is mixed with #39 in #40. They should be the separate commit.

**Comment by jameslu77** [comment]
It's done.
See detail at PR #40.
