### ISSUE TITLE
The tunnel module should be added to the lint formatter

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#346]
The tunnel module should be added to the lint formatter.

**Comment by edsburke** [comment]
@jameslu77  This one is re-assigned to you. Thanks.

**Comment by jameslu77** [comment]
Done at PR #393.
[ISSUE-346.000.txt](https://github.com/wallchainfoundation/wallchain/files/2599867/ISSUE-346.000.txt)
