### ISSUE TITLE
Support calling NodeRpcClient::FindNodes should without the sender info

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallchain#358]
Current FindNodes requires the sender information. It works when the caller itself is a node.
```
void NodeRpcClient::FindNodes(
    ReturnCodePtr return_code,
    const NodeId &key,
    const uint16_t &nodes_requested,
    const Contact &sender,
    const Contact &peer,
    RpcFindNodesFunctor callback) {
```

But it doesn't work for the caller who is not a node but a client only, e.g. an http server. Therefore it should support calling FindNodes without the sender info.

**Comment by jameslu77** [comment]
Now NodeRpcClient::FindNodes supports calling with empty sender like:
```
client.FindNodes(ret, target_id, 2, Contact(), peer, callback);
```
[ISSUE-358.000.txt](https://github.com/wallchainfoundation/wallchain/files/2568528/ISSUE-358.000.txt)

**Comment by edsburke** [comment]
@jameslu77 thanks for the commit. A quick question for you, why is this commented out in TEST_F(NodeRpcClientTest, RpcFindNodesFunctor)

```
      const ReturnCode &return_code,
      const std::vector<Contact>& contacts) {
    EXPECT_EQ(contact_.endpoint(), info->endpoint);
    EXPECT_LT(0, info->rtt);
//    EXPECT_LT(0, info->rtt);
```
