### ISSUE TITLE
Use wallchain::rpc namespace for RPC module

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#38]
1. Use wallchain::rpc namespace
1.  wallchain/rpc directory should be created accordingly under include and src dirs.
1. Move src/test to src/wallchain/rpc
1. Change cmake to reflect new namespace
1. Change #include in sources to reflect new namespace
1. Change proto files under src/if to reflect new namespace
1. ......

**Comment by jameslu77** [comment]
It's done.
See detail at PR #48.
