### ISSUE TITLE
"LOG" is redefined in Common and Rpc

### ISSUE THREAD

**Issue by jameslu77** [wallchainfoundation/wallchain#39]
Sub-project Common defines a macro named "LOG", and Rpc is using glog which having a macro with the  same name.

**Comment by jameslu77** [comment]
This issue is fixed by renaming LOG in common to MLOG, TLOG to TMLOG.
Check detial in PR #40

**Comment by xiaobingo** [comment]
This has been reopened because with commit is mixed with #34 in #40. They should be the separate commit.

**Comment by jameslu77** [comment]
This is a portion of the job to import the Rpc as a sub-module. It's fixed.
See detail at PR #40.
