### ISSUE TITLE
Use cpplint to format source

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#42]
The readable code format is quite important to maintain source. Cpplint is used to format source before it's committed to repo.

Ideally, cpplint should be hooked into cmake so as to make code formatting automatic, however, given that there is much third-party code which is not compliant with cpplint rules, we run cpplint manually so far.

**Comment by xiaobingo** [comment]
Re-assign it to @jameslu77. Please use [google styleguide](https://github.com/google/styleguide), cpplint especially to format sources before committing them.

This [cpplint.sh](https://github.com/apache/hbase/blob/HBASE-14850/hbase-native-client/bin/cpplint.sh) is a good start you can count on.

**Comment by xiaobingo** [comment]
Note that we strictly follow [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) in Wallchain project.

**Comment by jameslu77** [comment]
Use cpplint to format 5 files. See at PR #77.
[ISSUE-42.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2381923/ISSUE-42.000.patch.txt)

**Comment by jameslu77** [comment]
Set up cpplint mechanism to check wallchain's sources. 
Just run: ./cpplintwallchain.sh on the root path of Wallchain.
See also PR #80.
[ISSUE-42.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2385295/ISSUE-42.001.patch.txt)
