### ISSUE TITLE
Generalize ServerPipelineFactory with template parameters

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#43]
ServerPipelineFactory requires two specialization parameters:
1. RpcXXXService
2. RpcXXXServerSerializeHandler

These two should be generalized with template parameters so that ServerPipelineFactory can be instantiated in a template paradigm for reusability.

**Comment by xiaobingo** [comment]
Resolved it due to PR#46.

**Comment by xiaobingo** [comment]
[ISSUE-43.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2369456/ISSUE-43.000.patch.txt)

**Comment by xiaobingo** [comment]
@jameslu77 could rebase this patch on master after committing #45? Thanks.

**Comment by jameslu77** [comment]
fixed.
[ISSUE-43.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2370563/ISSUE-43.001.patch.txt)
See also PR #49
