### ISSUE TITLE
Use wallchain.rpc.pb as package name in proto file

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#51]
To distinguish the regular classes from PB classes, it's better to have one more level namespace, e.g. wallchain.rpc.pb

**Comment by jameslu77** [comment]
It's done.
[ISSUE-51.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2373503/ISSUE-51.000.patch.txt)
See also at PR #62 .
