### ISSUE TITLE
Revise old package/comment contents in rpc/if/*.proto

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#55]
Something like this <option java_package = "org.apache.hadoop.hbase.protobuf.generated";> should be revised to, e.g. 
option java_package = "net.wallchain.rpc.protobuf.generated";

**Comment by jameslu77** [comment]
It's done.
[ISSUE-55.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2373258/ISSUE-55.000.patch.txt)
See also at PR #59.
