### ISSUE TITLE
Add how-to instructions of <Docker build environment> for Linux

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#63]
It's advised to follow [How To Install and Use Docker on Ubuntu 16.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04)
1. follow step 1
1. optionally run step 2
1. run bin/start-docker.sh

Instruction should go to README.

**Comment by xiaobingo** [comment]
Since #67 configures docker container to have 4GB memory, please clarify that a docker host needs at least 4GB memory to let container run correctly.

**Comment by wupeng191** [comment]
See [ISSUE-63-001.txt](https://github.com/wallchainfoundation/wallchain/files/2386491/ISSUE-63-001.txt)
please review.

**Comment by wupeng191** [comment]
Done at PR  #104

**Comment by jameslu77** [comment]
@wupeng191 
There is an error when running: git am --signoff < ISSUE-63-001.txt. 
Please fix it and recommit/PR.

**Comment by xiaobingo** [comment]
Also use the format: ISSUE-63.00X.patch @wupeng191 @jameslu77

**Comment by wupeng191** [comment]
Done at PR # #108 .
[ISSUE-63.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2400117/ISSUE-63.001.patch.txt)
TO APPLY A PATCH
- git am --signoff  < patch_files/ISSUE-63.001.patch.txt.

If warning: 1 line adds whitespace errors, don't  care.

Use following  command to ignore this warning for next apply:
- git config apply.whitespace nowarn

**Comment by wupeng191** [comment]
Solved.
