### ISSUE TITLE
Add license/copyright disclaimer for newly added sources in routing module

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#66]
1. Newly added sources in RPC module will use LGPL.
1. Newly added sources in routing and other modules being built atop common will use GPL since common is GPL licensed.

Copyright:
Wallchain
Copyright 2018-Present The Wallchain Foundation

This product includes software developed at The Wallchain Foundation.

Note that:
1. The sources based on GPL licensed ones must be GPL licensed.
1. GPL sources can use LGPL or Apache licensed sources.

GPL is more strict than LGPL. The idea is:
The sources must be licensed at least as strict as sources on which the formers are based on.

**Comment by xiaobingo** [comment]
Please follow this [LGPL license claim] (https://github.com/wallchainfoundation/wallchain/pull/76/commits/5e07460dca81950c47cd4abfc98b9f53cdbeda3a)

**Comment by xiaobingo** [comment]
@wupeng191 please check with @jameslu77 how to proceed.

Note that:
1. all newly added files in RPC module must be LGPL licensed.
1. all newly added files in routing, common, and so on must be GPL licensed.

@wupeng191 please checkout git commit log to find newly added files and put proper license disclaimer in.

**Comment by xiaobingo** [comment]
@jameslu77 It will be efficient if everybody changes the source files he or she added. So assign this ticket to you and me.

**Comment by xiaobingo** [comment]
@jameslu77  do it for your part. I will file a sibling ticket.

**Comment by jameslu77** [comment]
Modify GPL licensed claim for newly sources at Routing.
See also at PR #92.
[ISSUE-66.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2391090/ISSUE-66.000.patch.txt)

**Comment by jameslu77** [comment]
It had been done at #102.
