### ISSUE TITLE
Prefix pb:: to some PB classes being omitted.

### ISSUE THREAD

**Issue by jameslu77** [wallchainfoundation/wallchain#75]
This is a follow-up issue of #70. There are still some PB classes need to pb:: prefixed.
Please check and fix it, thanks!

**Comment by wupeng191** [comment]
Done at PR #118 .
[ISSUE-75.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2407270/ISSUE-75.001.patch.txt)

**Comment by jameslu77** [comment]
There're still some class needed to use Prefix "pb::". 
A key to check that is search by "using namespace wallchain::rpc::pb;".
Please fix again, thanks!

**Comment by wupeng191** [comment]
Update at PR #119 .
[ISSUE-75.002.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2407505/ISSUE-75.002.patch.txt)

**Comment by jameslu77** [comment]
OK, It's done.
