### ISSUE TITLE
Add license/copyright disclaimer for newly added sources in RPC module

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#83]
This is sibling ticket of #66.

**Comment by edsburke** [comment]
Resolve this due to #179

**Comment by edsburke** [comment]
[ISSUE-83.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2425238/ISSUE-83.000.patch.txt)

**Comment by edsburke** [comment]
Posted [ISSUE-83.001.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2425263/ISSUE-83.001.patch.txt)
