### ISSUE TITLE
Add coding style in README

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#97]
Please add coding style in README. Wallchain project blatantly follows Google C++ coding style. Please also include a link to it.

**Comment by jameslu77** [comment]
Done at PR #105.
[ISSUE-97.000.patch.txt](https://github.com/wallchainfoundation/wallchain/files/2396263/ISSUE-97.000.patch.txt)
See also: [Google C++ coding style](https://google.github.io/styleguide/cppguide.html)
