### ISSUE TITLE
Add instruction that stipulates executing code style formatter for all commits.

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#98]
Code style formatter (e.g. cpplintwallchain.sh) should be executed before a commit is pushed to master branch or dev branch as well. It's better to have them in README.

**Comment by jameslu77** [comment]
See detail at [Wallchain code style](https://github.com/wallchainfoundation/wallchain/blob/master/dht/README.md).
Also see issue #97.
