### ISSUE TITLE
Add space only tab (i.e. two spaces) and 100-line length to coding style.

### ISSUE THREAD

**Issue by xiaobingo** [wallchainfoundation/wallchain#99]
Wallchain uses the style of space only tab (i.e. two spaces) and 100-line length in all sources. This should be part of coding style.

[cpplintwallchain.sh](https://github.com/wallchainfoundation/wallchain/blob/master/cpplintwallchain.sh) will enforce 100 line length at least.

**Comment by jameslu77** [comment]
The cpplintwallchain.sh is already meet the demand.
It enforces 100 line length at most.
